version: "3.8"
services:
  web:
    depends_on:
      - postgres_db
      - api
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    build: 
      context: ./app
      dockerfile: Dockerfile
  api:
    ports:
      - 8042:8042
    build: 
      context: ./api
      dockerfile: Dockerfile
    
  postgres_db:
    image: postgres
    restart: always
    env_file:
      - ./app/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: