# Generated by Django 5.0.2 on 2024-03-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(default="Las Vegas", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.BooleanField(
                blank=True,
                choices=[(0, "Incapacité de rembourser"), (1, "Capable de rembourser")],
                null=True,
            ),
        ),
    ]
