# Generated by Django 5.0.2 on 2024-03-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_company_city_alter_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="real_estate",
            field=models.CharField(choices=[("Y", "Oui"), ("N", "Non")], max_length=1),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[(0, "Incapacité de rembourser"), (1, "Capable de rembourser")],
                max_length=1,
                null=True,
            ),
        ),
    ]
