# Generated by Django 4.2.10 on 2024-03-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_request_real_estate_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Incapacité de rembourser'), ('1', 'Capable de rembourser')], max_length=1, null=True),
        ),
    ]
